name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-push:
    uses: bmgalhardo/ci/.github/workflows/external-docker.yml@main
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
